language: java
jdk:
  - oraclejdk11

install: skip

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lucas.cs.simonini@gmail.com
on_success: always
on_failure: always