version: "3"
services:
  database:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=restaurants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432